### ISSUE TITLE
ckpt to h5

### ISSUE THREAD

**Issue by sourav22899** [DTaoo/VGGish#6]
@DTaoo The original checkpoint file is provided [here](https://storage.googleapis.com/audioset/vggish_model.ckpt). How did you generate a HD5 file without retraining the model ?

**Comment by beasteers** [comment]
@sourav22899 I have an updated VGGish Keras implementation which includes a conversion script [vggish_keras/download_helpers/convert_ckpt.py](https://github.com/beasteers/VGGish/blob/master/vggish_keras/download_helpers/convert_ckpt.py). 

For it to work, you need:
 - vggish_keras installed (https://github.com/beasteers/VGGish)
 - openmic installed (https://github.com/cosmir/openmic-2018.git)
 - to have run: `openmic-2018/scripts/download_deps.sh`

The main difference is that I load weights with `by_name=True`, so I only create a single weights file (that can be used with or without the top). The weights file also includes the post-processing weights which can optionally be added to the top like in the original implementation.

**Comment by sourav22899** [comment]
Thanks for the reply.
